* Causal inference in earth science


** Introduction

questions: where/if discuss causal discorvery (may be necessary for
terminology, discovery papers like runge review use "causal inference"
terminology)? - think should have separate section for this.

questions: discuss hannart attribtion and counterfactuual paper?

*** usefullness causal inference e.s.


    Causal inference is the estimation of effects (e.g. temperature)
    in response to changes in causes (e.g. green house gas
    concentration) using observational data from a system. Causal
    inference is an alternative path towards scientific discovery,
    which traditionally relies on experimentation (e.g. numerical,
    lab, or real world) to determine the effect of varying causes. In
    earth sciences in particular it may be impossible or unethical to
    execute real world experiments, and numerical experiments may rely
    on approximations that bias causal estimates relative to the real
    world. Given these challenges in earth science, causal inference
    from data is a tantilizing tool that allows for robust
    estimatation of causal effects that may be otherwise impossible
    using traditoinal tools.

*** challenges of ci in e.s.

    However, causal inference from data presents its own challenges. A
    necessary conditon for calculating a causal effect is that the
    causal effect must be identifiable from the set of observable
    variables. Whether or not a causal effect is identifiable is
    determined from our assumptions about how a system behaves and
    which variables we can obtain observations for. If an effect is
    determined to be unidentifable, then it is impossible to calculate
    the causal effect of interest, even with an infitinte sample of
    data. Specific to problems in earth science, the identification of
    causal effects is challenging given two fundamental properties of
    many generic earth science problems: the system evolves through
    time according to an underlying dynamical system, and we only ever
    partially observe the state space of that dynamical system. Using
    graph theory developed in \citep{pearl-1995} we determine the
    generic problems causal inference is justified for, and the
    necesarry assumptions for applyign causal inference. The theory
    suggest there is the potential for applying causal inference at
    the human-climate interface (e.g. anthropogenic green house gas
    emission, land use change) (Secion xx), as well as for
    understanding the behavior of the natural system if we can
    estimate the state space of the system from observations and
    assume that our causes and effects have a negligble effect on the
    evolution of the larger state space (Section xx). Along the way,
    we introduce causal inference theory, causal graphs, and do
    calculus for the unfamiliar reader (Section xx), and compare with
    recent earth science literature on the related field of Causal
    Discovery. Causal graphs are also a useful general research tool
    for communicating assumptions, whether or not causal inference is
    actually used (Section xx).


** Causal graphs and Pearl's do calculus

*** intro causal graphs
   Causal graphs, introduced in citep{pearl-1995}, are directed
   acyclic graphs (DAGs) that encode our assumptions about the causal
   dependencies of a system. One draws directed edges (e.g. arrows)
   from variables that are causes to effects. To illustrate, in a
   simplified toy example examing clouds, aerosols, and surface solar
   radiation, we would draw (Figure xx):

   1. An arrow from aerosols to clouds because aerosols serve as cloud
      condensation nuclei.
   2. An arrow from aerosols to surface solar radiation, because
      aerosols can reflect sunlight back to space and reduce sunlight
      at the surface.
   3. An arrow from clouds to surface solar ratiation, because clouds
      also reflect sunlight back to space and can reduce sunlight at
      the surface.

   Causal graphs encode our assumptions about how the system behaves,
   and the nodes and edges that are missing from the graph often
   represent strong assumptions about how the system works. For
   example, in the cloud-aerosol-sunlight example, clouds also affect
   aerosols by increasing the likelihood that aerosol will be scoured
   from the atmosphere as precipitatation. By not including an edge
   from cloud to aerosol, we are making a strong assumption that we
   are ignoring this effect of clouds on aerosols. Cosidering this
   example isintended to be pedagocical for introducing causal theory to the
   readers, we will continue with the graph as drawn in Figure
   xx. Causal graphs are very useful tools because they can be drawn
   by any domain expert with no required knowledge of math or
   probability, but they also represent formal mathetmical objects
   with very sepcific meanings (discuss factorization of joint?)

*** intro identification

    Given their mathematical meaning, we can use causal graphs to
    identifiy which distributions we must estimate from data in order
    to calcualte a causal effect of itnerest. This process of
    identifying the necessary distributions is formally termed
    /causal indentification/. If a causal effect is not
    identifiable (/un/-identifiable), for example if
    calculating a causal effect requires distributions of variables
    that we do not observe, then we cannot use causal inference to
    caluclate a causal effect, even with an infinite sample of data.

*** backdoor path

    One necessary condition for un-identifablility is the presence of
    an unblockable backdoor path from cause to effect. This led to the
    early and well studied sufficient condition for identificatication
    called the /backdoor criterion/. The backdoor criterion
    states that if we can observe variables such that the backdoor
    paths from cause to effect are blocked, then a causal effect is
    identified. Backdoor paths are any paths going through parents of
    the cause, to the effect. We can block these paths by selectively
    observing observing cariables such that no information passes
    along them. Perhaps a mor eintuitive explanation is if we remove
    all edges from the cause to the cause's children, and then ask the
    question, "is the cause independent of the effect?". If the answer
    is yes, then calcuating our causal effect is identified. If the
    answer is no, then we must observe some variables such that the
    cause becomes independent of the effect, in the mutilated
    graph. This matches intuition: we only want to calculate the
    co-variability of our cause and effect due to information
    travelling fromt he cause to the effect along directed causal
    pathways, not due to parent processes inducing covariability in
    both the cause and effect. In other words, in the absence of
    backdoor paths, correltion is causation.

*** backdoor path with example

    Perhaps backdoor paths and the backdoor criterion are better introduced with an
    example. Returning to out toy example Figure xx, we will attempt
    to calcualte the causal effect of clouds on sunlight. In
    otherwords, we want to isolate the variability of sunlight due to
    the causal link from cloud to sunight. However, aerosols both
    effect cloud (edge from aerosol to cloud), and sunlight, so if we
    naively were to calculate a causal effect for example by just
    regressing sunlight on cloud, we would get a biased estimate of
    the mean causal effect of cloud on sunlight. This can be shown
    graphically if we remove all edges from our cause (cloud) to
    children of our cause (in this case sunlight) (Figure xx). We see
    that cloud is not indepednent fo aerosol in the mutilated
    graph. How would we make cloud and sunlgith independent in this
    mutiliated graph? In this case, by observing
    aerosol. Mathematically, the
    identification of the causal effect of cloud and aerosol accoridng
    to the backdoor criterion is:

    \begin{equation}
      P(sunlight | do(cloud) = c) = \Int_{aerosol} p(sunlight| cloud = c,
      aerosol) p(aerosol)),
    \end{equation}

    % introduce ATE?

    where we have implicitly introduced Pearl's "do" calculus, which
    just means we want to calculate the effect of intervene on our
    cause and setting it to some value of our choosing. In the case
    that observations of aerosols are not available, our causal effect
    is not identifiable and we cannot use causal effect no matter how
    large the sampel sizes of clouds and aerosols. This theory is an
    elegant tool: without having to touch data or estimate marginal or
    conditional distribution, we can determine whether it is possible
    to calcualte a causal effect of intereste. We later use this
    thoery to theoretically assess which problems are tractable in
    earth science using causal inference.

*** other identification strategies focusing on backdoor path

    Here we focus on the backdoor criterion. However, other
    identification stregies exist, primarily the front-door criterion
    and instrument variables. Given the timeseries nature of our
    problems (Section XX), front-door criterion and instrument varialbes
    are less likely to be useful for identification in earth science,
    so we will primarily use the backdoor criterion in our subsequent
    theoretical analysis. However please consult citeXX and cite XXX
    for more information on the front-door criterion and instrument
    variables.

** Clarification on terminology and relationship to literature on causal discovery

*** causal discovery = infering causal graph from data

    In this paper we discuss causal inference, and define it as
    estimating the induced effect of intervening on a cause and
    setting it or changing it to some value. However "causal
    inference" has also been used previously to describe the process
    of inferring /the edges in a causal graph/ from data. To be
    consisstent with previous literature in the causal community, we
    call this technique of of infering the graph structure from data
    /causal discovery/, whiel calculating causal effects given a graph
    and data is /causal inference/. There has been cosiderable  recent
    focus on /causal discovery/ in earth science, so it is worth it to
    discuss a little more on the relationship between causal inference
    and causal discovery and how it relates to earth science.

*** often times we know causal graph (can write down equations)

    Often in earth science we know, or have a strong a priori belief,
    about what the causal graph of our system most likely looks
    like. For example, in the climate system we know the dependencies
    of variables, even if we cannot write down the exact functional
    forms of these dependencies (especially for processes like
    trubulence and clouds). So, we can write down a causal graph and
    do not need to infer the dependenceies from data. Given these
    observations one might question why the itnerest in causal
    discovery for earth science. One possible explanation is the
    causal discovery may be useful to remove edges that have a small
    or negligble effect. For example, a prior we may know that some
    process is a function of three other processes, and perhaps in
    reality one o these processes negligbly effects the
    fucntion. Causal discovery would remove that edge.

*** resulting causal graph will be function of significance paramters

    However, the inferred graph in  causal discovery will be a
    function of the significance parameters used to determine
    conditoinal independence between variables upon which the
    algorithms rely on to determine edges and directions of edges in
    the graph. So, given that causal discovery algorhtms can produce
    potentially arbitraty results as a function of hyperparameters of
    the method, it may be methodloically safter to build a causal
    graph using expert knowledge. Especially when it is still possible
    to test if the causal graph is consistent with observations using
    conditional independence tests.

*** many pitfalls of causal discovery same as for causal inference


# put in this section? think important to discuss regression and
# problems of conditioning on variables that are in the causal path.
# ** Causal graphs: a tool for communicating assumptions and avoiding flawed experiments
# *** A tool for communicating assumptions

# *** Avoiding flawed experiment designs

** Applications in earth science: pitfalls and justified approaches for generic scenarios

*** Earth science as a dynamical system with partial observations of the state space

*** Tractable approach: the human-climate interface

*** Tractable approach: estimating the state space with Takens' theorem, and separating it from the cause and effect

** Discussion

   discuss transportability?

   discuss relationship of these ideas to causal discovery (critique
   causal discovery)?

   discuss issues with data available and observed range
   (e.g. generalization for cliamte research)?
