* Repository for the manuscript "[[https://arxiv.org/abs/2105.00912][Causal inference for process understanding in Earth sciences]]" by Adam Massmann, Pierre Gentine, and Jakob Runge

** Reproducibility notes
   This manuscript was successfully reproduced on May 9, 2022, on
   Debian GNU/Linux 11 (bullseye). However, there were some caveats:

   - There seems to be some nondeterminism in different releases of
     ~mwc-random~: ~create~ in ~System.Random.MWC~ uses a fixed seed,
     but it appears that fixed seed is different now than it was when
     I first wrote the manuscript (results in a random fluctuation of
     the estimated causal effect of < 1 W/m^2). Not ideal, but to put
     a positive spin on it each new version could be thought of as an
     independent check on the paper's ideas - we wouldn't want the
     conclusions to be dependent on the random seed!
   - The default fontsize/fonttype appears to change for graphviz/dot:
     in the reproduced version the ~ccope.pdf~ figure was off the
     page, and I had to manually adjust the fontsize in ~ccope.dot~ to
     make it fit. It fits for now on Debian 11, but future versions
     could change again.


** Required software

   - [[https://www.tug.org/texlive/][texlive]] (tested on 2019)
   - [[https://www.haskell.org/downloads/#minimal][Haskell GHC compiler and Cabal build tool]]
   - [[https://www.graphviz.org/][Graphviz]]
   - [[http://www.gnuplot.info/][gnuplot]]
   - [[https://www.ghostscript.com/][ghostscript]]

** Build instructions
*** Windows (untested)

    Clone this repository, enter directory, and run:

    #+BEGIN_SRC bash
    cabal v2-run build
    #+END_SRC

*** GNU/Linux (and OSX?) instructions

    Clone this repository, enter directory, and run:

    #+BEGIN_SRC bash
    cabal v2-run build
    #+END_SRC

    or, with GNU Make:

    #+BEGIN_SRC bash
    make
    #+END_SRC

    This should also probably work on OSX, but I haven't tested it.

** Directory structure
   ~doc/~ contains the paper, ~dot/~ contains source files Graphviz
   figures, ~gnuplot/~ contains source files for gnuplot figures,
   ~src/~ contains haskell code for generating data and figures.

** Contributions

   We will update this manuscript as our understanding of causality's
   role in Earth science research evolves. Comments, feedback, and edits
   are enthusiastically encouraged, and we will add acknowledgments
   and/or coauthors as we receive community contributions. To edit the
   manuscript directly (recommended) you can fork the project's
   repository and submit a pull request, or you can alternatively email
   us comments, questions, and suggestions and we will try to incorporate
   them into the manuscript.
